#!/bin/bash
# Script to generate the config.h.in template for LibRift
# Copyright (c) 2025 LibRift Project

set -e

# Check if config.h.in already exists in source tree
if find "${CURDIR:-$(pwd)}/src" -name "config.h.in" -print -quit | grep -q .; then
    echo "Found existing config.h.in in source tree, copying..."
    cp "$(find "${CURDIR:-$(pwd)}/src" -name "config.h.in" -print -quit)" ./config.h.in
    exit 0
fi

# Generate the template file
cat > config.h.in << 'TEMPLATE_END'
/**
 * @file config.h
 * @brief LibRift configuration settings
 *
 * Auto-generated configuration file for LibRift.
 * Do not edit this file directly - modify config.h.in instead.
 *
 * @copyright Copyright (c) 2025 LibRift Project
 * @license MIT License
 */

#ifndef LIBRIFT_CONFIG_H
#define LIBRIFT_CONFIG_H

/* Version information */
#define LIBRIFT_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define LIBRIFT_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define LIBRIFT_VERSION_PATCH @PROJECT_VERSION_PATCH@
#define LIBRIFT_VERSION_STRING "@PROJECT_VERSION@"

/* Feature configuration */
#cmakedefine LIBRIFT_USE_MEMORY_POOL
#cmakedefine LIBRIFT_ENABLE_REGEX_SYNTAX
#cmakedefine LIBRIFT_ENABLE_VISUALIZER

/* Platform capabilities */
#cmakedefine HAVE_STDINT_H
#cmakedefine HAVE_STDBOOL_H
#cmakedefine HAVE_REGEX_H

/* Build configuration */
#cmakedefine LIBRIFT_DEBUG_MODE

/* Implementation constants */
#define LIBRIFT_MAX_STATES @LIBRIFT_MAX_STATES@
#define LIBRIFT_MAX_TRANSITIONS @LIBRIFT_MAX_TRANSITIONS@
#define LIBRIFT_MAX_BACKTRACKING_DEPTH @LIBRIFT_MAX_BACKTRACKING_DEPTH@

#endif /* LIBRIFT_CONFIG_H */
TEMPLATE_END

echo "Generated config.h.in template"
