/**
 * @file validator.h
 * @brief Header file for the regex validator component of LibRift
 *
 * This file defines the interface for validating Abstract Syntax Trees (ASTs)
 * that represent regular expressions in the LibRift regex engine.
 *
 * @copyright Copyright (c) 2025 LibRift Project
 * @license MIT License
 */

#include <stdarg.h>
#include <stdbool.h>
#include "core/automaton/flags.h"
#include "core/errors/regex_error.h"
#include "core/parser/ast.h"
#ifndef LIBRIFT_REGEX_PARSER_VALIDATOR_H
#define LIBRIFT_REGEX_PARSER_VALIDATOR_H



#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Maximum length of error messages generated by the validator
 */
#define RIFT_REGEX_VALIDATOR_MAX_ERROR_LENGTH 256

/**
 * @brief Validator opaque structure
 */
typedef struct rift_regex_validator rift_regex_validator_t;

/**
 * @struct rift_regex_validator
 * @brief Internal structure of the validator
 */
struct rift_regex_validator {
    char error[RIFT_REGEX_VALIDATOR_MAX_ERROR_LENGTH]; /**< Error message buffer */
    rift_regex_flags_t flags;                          /**< Flags that affect validation */
    size_t max_group_number;                           /**< Maximum group number seen */
    size_t current_group_number;                       /**< Current group number being processed */
    size_t max_recursion_depth;                        /**< Maximum recursion depth allowed */
    size_t current_recursion_depth;                    /**< Current recursion depth */
};
/**
 * @brief Create a new validator
 *
 * @return A new validator instance or NULL on failure
 */
rift_regex_validator_t *rift_regex_validator_create(void);

/**
 * @brief Free resources associated with a validator
 *
 * @param validator The validator to free
 */
void rift_regex_validator_free(rift_regex_validator_t *validator);

/**
 * @brief Validate an AST
 *
 * @param validator The validator
 * @param ast The AST to validate
 * @return true if the AST is valid, false otherwise
 */
bool rift_regex_validator_validate(rift_regex_validator_t *validator, const rift_regex_ast_t *ast);

/**
 * @brief Validate an AST with specific flags
 *
 * @param validator The validator
 * @param ast The AST to validate
 * @param flags Flags that affect validation
 * @return true if the AST is valid, false otherwise
 */
bool rift_regex_validator_validate_with_options(rift_regex_validator_t *validator,
                                                const rift_regex_ast_t *ast,
                                                rift_regex_flags_t flags);

/**
 * @brief Get the last error message
 *
 * @param validator The validator
 * @return The last error message or NULL if no error occurred
 */
const char *rift_regex_validator_get_last_error(const rift_regex_validator_t *validator);

/**
 * @brief Validate a specific AST node
 *
 * @param validator The validator
 * @param node The node to validate
 * @return true if the node is valid, false otherwise
 */
bool rift_regex_validator_validate_node(rift_regex_validator_t *validator,
                                        const rift_regex_ast_node_t *node);

/**
 * @brief Validate an alternation node
 *
 * @param validator The validator
 * @param node The alternation node to validate
 * @return true if the node is valid, false otherwise
 */
bool rift_regex_validator_validate_alternation(rift_regex_validator_t *validator,
                                               const rift_regex_ast_node_t *node);

/**
 * @brief Validate a quantifier node
 *
 * @param validator The validator
 * @param node The quantifier node to validate
 * @return true if the node is valid, false otherwise
 */
bool rift_regex_validator_validate_quantifier(rift_regex_validator_t *validator,
                                              const rift_regex_ast_node_t *node);

/**
 * @brief Validate a group node
 *
 * @param validator The validator
 * @param node The group node to validate
 * @return true if the node is valid, false otherwise
 */
bool rift_regex_validator_validate_group(rift_regex_validator_t *validator,
                                         const rift_regex_ast_node_t *node);

/**
 * @brief Validate a character class node
 *
 * @param validator The validator
 * @param node The character class node to validate
 * @return true if the node is valid, false otherwise
 */
bool rift_regex_validator_validate_character_class(rift_regex_validator_t *validator,
                                                   const rift_regex_ast_node_t *node);

/**
 * Validates the transitions between nodes in a regex abstract syntax tree.
 *
 * This function checks if the transitions between the given node and its
 * connected nodes comply with the regex grammar rules. It's used during
 * the validation phase of regex compilation.
 *
 * @param validator Pointer to the regex validator context
 * @param node Pointer to the AST node whose transitions need validation
 * @return true if all transitions are valid, false otherwise
 */
/**
 *  */                                       // Forward declaration of static function
static bool validate_node_transitions(rift_regex_validator_t *validator,
                                      const rift_regex_ast_node_t *node);
#ifdef __cplusplus
}
#endif

#endif /* LIBRIFT_REGEX_PARSER_VALIDATOR_H */