/**
 * @file string_pattern_detector.c
 * @brief Example: Detect and validate various string patterns using RIFT library
 *
 * This example demonstrates how to use all three public APIs:
 * - R"" (rift.h) - Core regex engine
 * - RTEST"" (rifttest.h) - Testing framework
 * - RLANG (riftlang.h) - Domain-specific language
 *
 * Build with: gcc -o string_pattern_detector string_pattern_detector.c -lrift -lm
 */

#include <rift/rift.h>
#include <rift/rifttest.h>
#include <rift/riftlang.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ============================================================================
 * Example 1: Using the Core API (R"")
 * ============================================================================ */

void example_core_api(void) {
    printf("\n=== EXAMPLE 1: Core API (R\"\") ===\n");
    printf("The core API provides direct access to the regex engine.\n");
    printf("Initialize with: librift_initialize()\n");
    printf("Use regex engine for pattern matching and compilation.\n");
    printf("Cleanup with: librift_cleanup()\n");
}

/* ============================================================================
 * Example 2: Using the Testing Framework (RTEST"")
 * ============================================================================ */

void example_testing_framework(void) {
    printf("\n=== EXAMPLE 2: Testing Framework (RTEST\"\") ===\n");

    // Pattern for detecting email addresses
    const char *email_pattern = "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}";

    // Create a test suite
    RTestSuite *suite = rtest_suite_create("String Pattern Tests", 10);

    // Test Case 1: Valid email
    RTestCase test1 = rtest_case_create(
        "Valid email address",
        email_pattern,
        "john.doe@example.com",
        true  // should match
    );
    rtest_suite_add(suite, test1);

    // Test Case 2: Email with numbers
    RTestCase test2 = rtest_case_create(
        "Email with numbers",
        email_pattern,
        "user123@company.co.uk",
        true
    );
    rtest_suite_add(suite, test2);

    // Test Case 3: Invalid - no @ symbol
    RTestCase test3 = rtest_case_create(
        "Invalid - no @ symbol",
        email_pattern,
        "notanemail",
        false  // should NOT match
    );
    rtest_suite_add(suite, test3);

    // Test Case 4: Invalid - no domain
    RTestCase test4 = rtest_case_create(
        "Invalid - missing domain",
        email_pattern,
        "user@",
        false
    );
    rtest_suite_add(suite, test4);

    // Run all tests
    printf("\nRunning test suite: %s\n", suite->name);
    bool all_passed = rtest_run_suite(suite);

    // Print results
    rtest_print_results(suite);

    if (all_passed) {
        printf("\n✓ All email validation tests PASSED!\n");
    } else {
        printf("\n✗ Some tests FAILED\n");
    }

    // Clean up
    rtest_suite_free(suite);
}

/* ============================================================================
 * Example 3: Using the DSL (RLANG)
 * ============================================================================ */

void example_dsl_language(void) {
    printf("\n=== EXAMPLE 3: Domain-Specific Language (RLANG) ===\n");

    // Create a RiftLang context
    RLangContext *ctx = rlang_context_create();

    // Define patterns using RiftLang DSL
    const char *rlang_source = R"RIFT(
        // Basic pattern components
        let digit = r"[0-9]"
        let alpha = r"[a-zA-Z]"
        let underscore = "_"
        let dot = "."
        let at = "@"
        let dash = "-"

        // Email pattern (LNAME @ DOMAIN . TLD)
        pattern email = {
            let local = alpha @ (alpha | digit | underscore | dot)*
            let domain = (alpha | digit | dash)+
            let tld = alpha @ "+"
            local @ at @ domain @ dot @ tld
        }

        // Phone pattern (US format: (XXX) XXX-XXXX)
        pattern phone_us = {
            "(" @ digit @ digit @ digit @ ")" @ " " @ digit @ digit @ digit @ dash @ digit @ digit @ digit @ digit
        }

        // URL pattern (http/https)
        pattern url = {
            ("http" | "https") @ "://" @ (alpha | digit | dash | dot)+ @ "/"?
        }
    )RIFT";

    // Compile the RiftLang program
    RLangCompileResult result = rlang_compile(ctx, rlang_source);

    if (result.success) {
        printf("✓ RiftLang compilation successful!\n");

        // List available patterns
        const char **pattern_names;
        size_t pattern_count;

        if (rlang_get_patterns(result.program, &pattern_names, &pattern_count)) {
            printf("\nAvailable patterns generated by RiftLang:\n");
            for (size_t i = 0; i < pattern_count; i++) {
                printf("  - %s\n", pattern_names[i]);

                // Execute each pattern to see the generated regex
                char *generated = rlang_execute_pattern(result.program, pattern_names[i]);
                if (generated) {
                    printf("    Pattern: %s\n", generated);
                    free(generated);
                }
            }
        }

        // Clean up program
        rlang_program_free(result.program);
    } else {
        printf("✗ RiftLang compilation failed: %s\n", result.error_message);
        rlang_compile_result_free(&result);
    }

    // Free the context
    rlang_context_free(ctx);
}

/* ============================================================================
 * Example 4: Combined Usage - All Three APIs
 * ============================================================================ */

void example_combined_usage(void) {
    printf("\n=== EXAMPLE 4: Combined Usage (All Three APIs) ===\n");
    printf("\nThis example shows how the three APIs work together:\n");
    printf("1. RLANG generates patterns from DSL\n");
    printf("2. RTEST validates those patterns\n");
    printf("3. R\"\" provides the core matching engine\n");

    // Create RiftLang context
    RLangContext *ctx = rlang_context_create();

    // Simple pattern: digits only
    const char *simple_dsl = "pattern digits = r\"[0-9]+\"";

    RLangCompileResult compile_result = rlang_compile(ctx, simple_dsl);

    if (compile_result.success) {
        // Get the generated pattern
        char *pattern = rlang_execute_pattern(compile_result.program, "digits");

        if (pattern) {
            printf("\nGenerated pattern from RLANG: %s\n", pattern);

            // Use RTEST to validate the pattern
            printf("\nValidating pattern with RTEST:\n");

            RTestSuite *suite = rtest_suite_create("Digit Validation", 5);

            rtest_suite_add(suite, rtest_case_create(
                "Valid digits", pattern, "12345", true
            ));

            rtest_suite_add(suite, rtest_case_create(
                "Invalid - letters", pattern, "abc123", false
            ));

            rtest_suite_add(suite, rtest_case_create(
                "Empty string", pattern, "", false
            ));

            rtest_run_suite(suite);
            rtest_print_results(suite);
            rtest_suite_free(suite);

            free(pattern);
        }

        rlang_program_free(compile_result.program);
    } else {
        printf("Compilation error: %s\n", compile_result.error_message);
        rlang_compile_result_free(&compile_result);
    }

    rlang_context_free(ctx);
}

/* ============================================================================
 * Main Entry Point
 * ============================================================================ */

int main(int argc, char *argv[]) {
    printf("╔════════════════════════════════════════════════════════════════╗\n");
    printf("║           RIFT Library: String Pattern Detector                ║\n");
    printf("║   Demonstrating R\"\", RTEST\"\", and RLANG APIs                 ║\n");
    printf("╚════════════════════════════════════════════════════════════════╝\n");

    // Initialize the library
    if (!librift_initialize()) {
        fprintf(stderr, "ERROR: Failed to initialize LibRift\n");
        return EXIT_FAILURE;
    }

    // Check version compatibility
    if (!librift_check_version()) {
        fprintf(stderr, "WARNING: Version mismatch\n");
    }

    // Run examples
    example_core_api();
    example_testing_framework();
    example_dsl_language();
    example_combined_usage();

    printf("\n╔════════════════════════════════════════════════════════════════╗\n");
    printf("║                      Examples Complete!                        ║\n");
    printf("║                                                                ║\n");
    printf("║  For more information, see USAGE_GUIDE.md                      ║\n");
    printf("╚════════════════════════════════════════════════════════════════╝\n\n");

    // Clean up
    librift_cleanup();
    return EXIT_SUCCESS;
}
