#include "rift/codec.h"

#include <stdio.h>
#include <string.h>

static rift_cir_kind_t classify_line(const char *line) {
    if (strstr(line, "govern")) return RIFT_CIR_GOVERN;
    if (strstr(line, "span")) return RIFT_CIR_SPAN;
    if (strstr(line, "while")) return RIFT_CIR_WHILE;
    if (strstr(line, "if")) return RIFT_CIR_IF;
    if (strstr(line, "return")) return RIFT_CIR_RETURN;
    if (strchr(line, '=')) return RIFT_CIR_ASSIGN;
    return RIFT_CIR_BLOCK;
}

int rift_link(const char *source, size_t length, rift_cir_program_t *out) {
    size_t start = 0;
    if (!source || !length || !out) return -1;
    memset(out, 0, sizeof(*out));

    while (start < length && out->node_count < RIFT_CIR_MAX_NODES) {
        size_t end = start;
        size_t copy_length;
        rift_cir_node_t *node;
        while (end < length && source[end] != '\n') end++;
        copy_length = end - start;
        while (copy_length && (source[start + copy_length - 1] == '\r' ||
                               source[start + copy_length - 1] == ' ' ||
                               source[start + copy_length - 1] == '\t')) {
            copy_length--;
        }
        if (copy_length) {
            if (copy_length >= sizeof(out->nodes[0].value)) {
                copy_length = sizeof(out->nodes[0].value) - 1;
            }
            node = &out->nodes[out->node_count++];
            memcpy(node->value, source + start, copy_length);
            node->value[copy_length] = '\0';
            node->kind = classify_line(node->value);
        }
        start = end + 1;
    }
    return 0;
}

static int emit_c(const rift_cir_program_t *program, FILE *stream) {
    int i;
    fputs("/* Generated by RIFT Is a Flexible Translator. */\n", stream);
    fputs("#include <stdio.h>\n\n", stream);
    fputs("int main(void) {\n", stream);
    fputs("    /* Canonical intermediate representation:\n", stream);
    for (i = 0; i < program->node_count; i++) {
        const char *line = program->nodes[i].value;
        fputs("       ", stream);
        while (*line) {
            if (line[0] == '*' && line[1] == '/') {
                fputs("* /", stream);
                line += 2;
            } else {
                fputc(*line++, stream);
            }
        }
        fputc('\n', stream);
    }
    fputs("    */\n", stream);
    fputs("    return 0;\n}\n", stream);
    return ferror(stream) ? -1 : 0;
}

static int emit_hexdump(const rift_cir_program_t *program, FILE *stream) {
    int i;
    static const char hex[] = "0123456789abcdef";
    for (i = 0; i < program->node_count; i++) {
        const unsigned char *value =
            (const unsigned char *)program->nodes[i].value;
        size_t j;
        for (j = 0; value[j]; j++) {
            fputc(hex[value[j] >> 4], stream);
            fputc(hex[value[j] & 0x0f], stream);
            if (value[j + 1]) fputc(' ', stream);
        }
        fputc('\n', stream);
    }
    return ferror(stream) ? -1 : 0;
}

int rift_codec_emit(const rift_cir_program_t *program, const char *target,
                    const char *output_path) {
    FILE *stream;
    int result;
    if (!program || !target) return -1;
    stream = output_path ? fopen(output_path, "wb") : stdout;
    if (!stream) return -1;

    if (strcmp(target, "c") == 0) result = emit_c(program, stream);
    else if (strcmp(target, "hexdump") == 0) result = emit_hexdump(program, stream);
    else result = -1;

    if (output_path) fclose(stream);
    return result;
}
