/**
 * @file config.h
 * @brief LibRift configuration settings
 *
 * Auto-generated configuration file for LibRift.
 * Do not edit this file directly - modify config.h.in instead.
 *
 * @copyright Copyright (c) 2025 LibRift Project
 * @license MIT License
 */

 #ifndef LIBRIFT_CONFIG_H
 #define LIBRIFT_CONFIG_H
 
 /* Version information */
 #define LIBRIFT_VERSION_MAJOR 1
 #define LIBRIFT_VERSION_MINOR 0
 #define LIBRIFT_VERSION_PATCH 0
 #define LIBRIFT_VERSION_STRING "1.0.0"
 
 /* Feature configuration */
 #define LIBRIFT_USE_MEMORY_POOL
 #define LIBRIFT_ENABLE_REGEX_SYNTAX
/* #undef LIBRIFT_ENABLE_VISUALIZER */
 
 /* Platform capabilities */
 #define HAVE_STDINT_H
 #define HAVE_STDBOOL_H
 #define HAVE_REGEX_H
 
 /* Build configuration */
/* #undef LIBRIFT_DEBUG_MODE */
 
 /* Implementation constants */
 #define LIBRIFT_MAX_STATES 1000
 #define LIBRIFT_MAX_TRANSITIONS 5000
 #define LIBRIFT_MAX_BACKTRACKING_DEPTH 1000
 
 #endif /* LIBRIFT_CONFIG_H */
